componentScriptContent: 
  - xmlizable: 
    - ↑classname: com.twinsoft.convertigo.beans.common.FormatedContent
    - com.twinsoft.convertigo.beans.common.FormatedContent: 
      →: |
        /*Begin_c8o_AppImport*/
        /*End_c8o_AppImport*/
        /*Begin_c8o_AppDeclaration*/
        	/*End_c8o_AppDeclaration*/
        /*Begin_c8o_AppConstructor*/
        		/*End_c8o_AppConstructor*/
        /*Begin_c8o_AppInitialization*/
                        /* Uncomment the following lines to enable the i18n feature.
                         * You should add a json per language in the assets/i18n folder. */
                        translate.setDefaultLang('en');
                        translate.use(translate.getBrowserLang());
                        
                        /* Uncomment the following lines to enable the custom status bar color. */
                        // statusBar.overlaysWebView(false);
                        // statusBar.backgroundColorByHexString("#000000");
                        // statusBar.styleBlackOpaque();
        			/*End_c8o_AppInitialization*/
        /*Begin_c8o_AppFunction*/
        	/*End_c8o_AppFunction*/
        
tplProjectName: mobilebuilder_tpl_8_0_0_ngx
↓Menu [ngx.components.UIDynamicMenu-1500890597895]: 🗏 mobileMenus/Menu.yaml
↓Xeokit3DViewer [ngx.components.UISharedRegularComponent-1643633500368]: 🗏 mobileSharedComponents/Xeokit3DViewer.yaml
↓Page [ngx.components.PageComponent-1500538678074]: 🗏 mobilePages/Page.yaml
↓Style [ngx.components.UIStyle-1491635462437]: 
  comment: You can add some global application styles here
  styleContent: 
    - xmlizable: 
      - ↑classname: com.twinsoft.convertigo.beans.common.FormatedContent
      - com.twinsoft.convertigo.beans.common.FormatedContent: 
        →: |
          'ion-menu ion-content {
            --background: var(--ion-item-background, var(--ion-background-color, #fff));
          }
          
          ion-menu.md ion-content {
            --padding-start: 8px;
            --padding-end: 8px;
            --padding-top: 20px;
            --padding-bottom: 20px;
          }
          
          ion-menu.md ion-list {
            padding: 20px 0;
          }
          
          ion-menu.md ion-note {
            margin-bottom: 30px;
          }
          
          ion-menu.md ion-list-header,
          ion-menu.md ion-note {
            padding-left: 10px;
          }
          
          ion-menu.md ion-list#inbox-list {
            border-bottom: 1px solid var(--ion-color-step-150, #d7d8da);
          }
          
          ion-menu.md ion-list#inbox-list ion-list-header {
            font-size: 22px;
            font-weight: 600;
          
            min-height: 20px;
          }
          
          ion-menu.md ion-list#labels-list ion-list-header {
            font-size: 16px;
          
            margin-bottom: 18px;
          
            color: #757575;
          
            min-height: 26px;
          }
          
          ion-menu.md ion-item {
            --padding-start: 10px;
            --padding-end: 10px;
            border-radius: 4px;
          }
          
          ion-menu.md ion-item.selected {
            --background: rgba(var(--ion-color-primary-rgb), 0.14);
          }
          
          ion-menu.md ion-item.selected ion-icon {
            color: var(--ion-color-primary);
          }
          
          ion-menu.md ion-item ion-icon {
            color: #616e7e;
          }
          
          ion-menu.md ion-item ion-label {
            font-weight: 500;
          }
          
          ion-menu.ios ion-content {
            --padding-bottom: 20px;
          }
          
          ion-menu.ios ion-list {
            padding: 20px 0 0 0;
          }
          
          ion-menu.ios ion-note {
            line-height: 24px;
            margin-bottom: 20px;
          }
          
          ion-menu.ios ion-item {
            --padding-start: 16px;
            --padding-end: 16px;
            --min-height: 50px;
          }
          
          ion-menu.ios ion-item.selected ion-icon {
            color: var(--ion-color-primary);
          }
          
          ion-menu.ios ion-item ion-icon {
            font-size: 24px;
            color: #73849a;
          }
          
          ion-menu.ios ion-list#labels-list ion-list-header {
            margin-bottom: 8px;
          }
          
          ion-menu.ios ion-list-header,
          ion-menu.ios ion-note {
            padding-left: 16px;
            padding-right: 16px;
          }
          
          ion-menu.ios ion-note {
            margin-bottom: 8px;
          }
          
          ion-note {
            display: inline-block;
            font-size: 16px;
          
            color: var(--ion-color-medium-shade);
          }
          
          ion-item.selected {
            --color: var(--ion-color-primary);
          }
          '
↓Theme [ngx.components.UITheme-1587022581006]: 
  styleContent: 
    - xmlizable: 
      - ↑classname: com.twinsoft.convertigo.beans.common.FormatedContent
      - com.twinsoft.convertigo.beans.common.FormatedContent: 
        →: |
          '// Ionic Variables and Theming. For more info, please see:
          // http://ionicframework.com/docs/theming/
          
          /** Ionic CSS Variables **/
          :root {
            /** primary **/
            --ion-color-primary: #3880ff;
            --ion-color-primary-rgb: 56, 128, 255;
            --ion-color-primary-contrast: #ffffff;
            --ion-color-primary-contrast-rgb: 255, 255, 255;
            --ion-color-primary-shade: #3171e0;
            --ion-color-primary-tint: #4c8dff;
          
            /** secondary **/
            --ion-color-secondary: #3dc2ff;
            --ion-color-secondary-rgb: 61, 194, 255;
            --ion-color-secondary-contrast: #ffffff;
            --ion-color-secondary-contrast-rgb: 255, 255, 255;
            --ion-color-secondary-shade: #36abe0;
            --ion-color-secondary-tint: #50c8ff;
          
            /** tertiary **/
            --ion-color-tertiary: #5260ff;
            --ion-color-tertiary-rgb: 82, 96, 255;
            --ion-color-tertiary-contrast: #ffffff;
            --ion-color-tertiary-contrast-rgb: 255, 255, 255;
            --ion-color-tertiary-shade: #4854e0;
            --ion-color-tertiary-tint: #6370ff;
          
            /** success **/
            --ion-color-success: #2dd36f;
            --ion-color-success-rgb: 45, 211, 111;
            --ion-color-success-contrast: #ffffff;
            --ion-color-success-contrast-rgb: 255, 255, 255;
            --ion-color-success-shade: #28ba62;
            --ion-color-success-tint: #42d77d;
          
            /** warning **/
            --ion-color-warning: #ffc409;
            --ion-color-warning-rgb: 255, 196, 9;
            --ion-color-warning-contrast: #000000;
            --ion-color-warning-contrast-rgb: 0, 0, 0;
            --ion-color-warning-shade: #e0ac08;
            --ion-color-warning-tint: #ffca22;
          
            /** danger **/
            --ion-color-danger: #eb445a;
            --ion-color-danger-rgb: 235, 68, 90;
            --ion-color-danger-contrast: #ffffff;
            --ion-color-danger-contrast-rgb: 255, 255, 255;
            --ion-color-danger-shade: #cf3c4f;
            --ion-color-danger-tint: #ed576b;
          
            /** dark **/
            --ion-color-dark: #222428;
            --ion-color-dark-rgb: 34, 36, 40;
            --ion-color-dark-contrast: #ffffff;
            --ion-color-dark-contrast-rgb: 255, 255, 255;
            --ion-color-dark-shade: #1e2023;
            --ion-color-dark-tint: #383a3e;
          
            /** medium **/
            --ion-color-medium: #92949c;
            --ion-color-medium-rgb: 146, 148, 156;
            --ion-color-medium-contrast: #ffffff;
            --ion-color-medium-contrast-rgb: 255, 255, 255;
            --ion-color-medium-shade: #808289;
            --ion-color-medium-tint: #9d9fa6;
          
            /** light **/
            --ion-color-light: #f4f5f8;
            --ion-color-light-rgb: 244, 245, 248;
            --ion-color-light-contrast: #000000;
            --ion-color-light-contrast-rgb: 0, 0, 0;
            --ion-color-light-shade: #d7d8da;
            --ion-color-light-tint: #f5f6f9;
          }
          
          @media (prefers-color-scheme: dark) {
            /*
             * Dark Colors
             * -------------------------------------------
             */
          
            body {
              --ion-color-primary: #428cff;
              --ion-color-primary-rgb: 66,140,255;
              --ion-color-primary-contrast: #ffffff;
              --ion-color-primary-contrast-rgb: 255,255,255;
              --ion-color-primary-shade: #3a7be0;
              --ion-color-primary-tint: #5598ff;
          
              --ion-color-secondary: #50c8ff;
              --ion-color-secondary-rgb: 80,200,255;
              --ion-color-secondary-contrast: #ffffff;
              --ion-color-secondary-contrast-rgb: 255,255,255;
              --ion-color-secondary-shade: #46b0e0;
              --ion-color-secondary-tint: #62ceff;
          
              --ion-color-tertiary: #6a64ff;
              --ion-color-tertiary-rgb: 106,100,255;
              --ion-color-tertiary-contrast: #ffffff;
              --ion-color-tertiary-contrast-rgb: 255,255,255;
              --ion-color-tertiary-shade: #5d58e0;
              --ion-color-tertiary-tint: #7974ff;
          
              --ion-color-success: #2fdf75;
              --ion-color-success-rgb: 47,223,117;
              --ion-color-success-contrast: #000000;
              --ion-color-success-contrast-rgb: 0,0,0;
              --ion-color-success-shade: #29c467;
              --ion-color-success-tint: #44e283;
          
              --ion-color-warning: #ffd534;
              --ion-color-warning-rgb: 255,213,52;
              --ion-color-warning-contrast: #000000;
              --ion-color-warning-contrast-rgb: 0,0,0;
              --ion-color-warning-shade: #e0bb2e;
              --ion-color-warning-tint: #ffd948;
          
              --ion-color-danger: #ff4961;
              --ion-color-danger-rgb: 255,73,97;
              --ion-color-danger-contrast: #ffffff;
              --ion-color-danger-contrast-rgb: 255,255,255;
              --ion-color-danger-shade: #e04055;
              --ion-color-danger-tint: #ff5b71;
          
              --ion-color-dark: #f4f5f8;
              --ion-color-dark-rgb: 244,245,248;
              --ion-color-dark-contrast: #000000;
              --ion-color-dark-contrast-rgb: 0,0,0;
              --ion-color-dark-shade: #d7d8da;
              --ion-color-dark-tint: #f5f6f9;
          
              --ion-color-medium: #989aa2;
              --ion-color-medium-rgb: 152,154,162;
              --ion-color-medium-contrast: #000000;
              --ion-color-medium-contrast-rgb: 0,0,0;
              --ion-color-medium-shade: #86888f;
              --ion-color-medium-tint: #a2a4ab;
          
              --ion-color-light: #222428;
              --ion-color-light-rgb: 34,36,40;
              --ion-color-light-contrast: #ffffff;
              --ion-color-light-contrast-rgb: 255,255,255;
              --ion-color-light-shade: #1e2023;
              --ion-color-light-tint: #383a3e;
            }
          
          }'